language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN=52ddd91d-56a5-402f-a8cd-0b2e0de9fc4e

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always